spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Eclassroom  # MySQL connection URL
    username: root  # Using the 'root' user
    password: ''  # No password (empty string)
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver class

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  graphql:
    graphiql:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
